# Generated by Django 4.0.4 on 2022-05-31 20:36

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.ImageField(default='default.png', upload_to=authentication.models.get_file_path, verbose_name='Profile Image'),
        ),
    ]
