# Generated by Django 4.0.5 on 2022-07-02 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('description', models.TextField(verbose_name='Post Description')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('img_url', models.ImageField(upload_to=portfolio.models.get_file_path, verbose_name='Post Image')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='Code Snippet')),
                ('code_snippet_language', models.CharField(blank=True, max_length=100, null=True)),
                ('code_url', models.URLField(blank=True, null=True, verbose_name='Url To Related Code')),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Post Comment')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted On')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='Code Snippet')),
                ('code_url', models.URLField(default='https://www.github.com/phillipmugisa', verbose_name='Url To Related Code')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='portfolio.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technology Field name')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted On')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Technology name')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted On')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Subscriber Email')),
                ('subscribed_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Subscribed On')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Subscriber Activated')),
            ],
            options={
                'ordering': ('-subscribed_on',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_file_path, verbose_name='Post Image')),
                ('production_url', models.URLField(blank=True, null=True, verbose_name='Project Production Url')),
                ('github_url', models.URLField(default='https://www.github.com/phillipmugisa', verbose_name='Project Github Url')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete')], default='Pending', max_length=50, verbose_name='Project Status')),
                ('origin', models.CharField(default='Admin', max_length=50, verbose_name='Project Source')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Owner's Email:")),
                ('field', models.ManyToManyField(related_name='Project_fields', to='portfolio.field')),
                ('stack', models.ManyToManyField(related_name='Project_stacks', to='portfolio.stack')),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
        migrations.CreateModel(
            name='ComComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment on comment')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload On')),
                ('reference_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='liked On')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='portfolio.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='field',
            field=models.ManyToManyField(to='portfolio.field'),
        ),
        migrations.AddField(
            model_name='blog',
            name='stack',
            field=models.ManyToManyField(to='portfolio.stack'),
        ),
    ]
