# Generated by Django 4.0.4 on 2022-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_comcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='Code Snippet'),
        ),
        migrations.AddField(
            model_name='blog',
            name='code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url To Related Code'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='code_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='Code Snippet'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url To Related Code'),
        ),
    ]
