# Generated by Django 4.0.4 on 2022-05-19 10:15

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_scrapednews_comcomment_added_on_alter_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_file_path, verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url'),
        ),
    ]
