# Generated by Django 4.0.4 on 2022-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_img_url_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='field',
            field=models.ManyToManyField(related_name='Blog_fields', to='portfolio.field'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='stack',
            field=models.ManyToManyField(related_name='Blog_stacks', to='portfolio.stack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='field',
            field=models.ManyToManyField(related_name='Project_fields', to='portfolio.field'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ManyToManyField(related_name='Project_stacks', to='portfolio.stack'),
        ),
    ]
