# Generated by Django 4.0.4 on 2022-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_blog_field_alter_blog_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code_snippet_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='field',
            field=models.ManyToManyField(to='portfolio.field'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='stack',
            field=models.ManyToManyField(to='portfolio.stack'),
        ),
    ]
