# Generated by Django 4.0.4 on 2022-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blog_code_snippet_language_alter_blog_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url'),
        ),
        migrations.AlterField(
            model_name='comcomment',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='Comment on comment'),
        ),
        migrations.AlterField(
            model_name='scrapednews',
            name='source',
            field=models.CharField(max_length=100, verbose_name='News Description'),
        ),
        migrations.AlterField(
            model_name='scrapednews',
            name='title',
            field=models.CharField(max_length=100, verbose_name='News Headline'),
        ),
    ]
