# Generated by Django 4.0.4 on 2022-05-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0011_remove_blog_likes_blogreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='https://www.github.com/phillipmugisa', verbose_name='Project Github Url'),
        ),
        migrations.AddField(
            model_name='project',
            name='production_url',
            field=models.URLField(blank=True, null=True, verbose_name='Project Production Url'),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='portfolio.blog'),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
