# Generated by Django 4.0.4 on 2022-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_end_date_project_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='code_url',
            field=models.URLField(default='https://www.github.com/phillipmugisa', verbose_name='Url To Related Code'),
        ),
    ]
