# Generated by Django 4.0.4 on 2022-05-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_blogcomment_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='code_url',
        ),
    ]
