# Generated by Django 4.0.4 on 2022-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_blogcomment_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='code_url',
            field=models.URLField(default='https://www.github.com/phillipmugisa', verbose_name='Url To Related Code'),
        ),
    ]
