# Generated by Django 4.0.4 on 2022-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_blogcomment_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapednews',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url'),
        ),
    ]
