# Generated by Django 4.0.4 on 2022-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_scrapednews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapednews',
            name='source',
            field=models.CharField(max_length=100, verbose_name='News Source'),
        ),
    ]
