# Generated by Django 4.0.4 on 2022-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_scrapednews_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapednews',
            name='news_url',
            field=models.URLField(default='', verbose_name='News Url'),
            preserve_default=False,
        ),
    ]
