# Generated by Django 4.0.4 on 2022-05-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_project_submitted_via_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='submitted_via',
            new_name='origin',
        ),
    ]
