# Generated by Django 4.0.4 on 2022-05-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_rename_submitted_via_project_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Owner's Email:"),
        ),
    ]
