# Generated by Django 4.0.4 on 2022-05-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_project_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='origin',
            field=models.CharField(default='Admin', max_length=50, verbose_name='Project Source'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete')], default='Pending', max_length=50, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Post Title'),
        ),
    ]
