# Generated by Django 4.0.4 on 2022-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_project_origin_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Post Title'),
        ),
    ]
