# Generated by Django 4.0.4 on 2022-05-28 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0026_alter_blog_options_alter_blogcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
