# Generated by Django 4.0.4 on 2022-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='img_url',
            field=models.URLField(max_length=500, verbose_name='Image Url'),
        ),
    ]
