# Generated by Django 4.0.4 on 2022-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrapper', '0002_alter_newsarticle_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(max_length=500, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='News Description'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=500, verbose_name='News Headline'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(max_length=500, verbose_name='News Source'),
        ),
    ]
